### ISSUE TITLE
В поле "Срок годности" можно поставить предыдущий день

### ISSUE THREAD

**Issue by brandonzorn** [Gray-Advantage/Datanar-Django#23]
![изображение](https://github.com/Gray-Advantage/Datanar-Django/assets/68778953/d25fa875-f85a-4d4c-a4ec-66302c7f058b)
## При нажатии сократить Ошибка 500
![изображение](https://github.com/Gray-Advantage/Datanar-Django/assets/68778953/181258f7-96e5-41a2-a4b5-1fedb565da6b)

**Comment by Gray-Advantage** [comment]
Я когда в первый раз посмотрел, я мог действительно указать дату в прошлое сейчас уже нет, видимо есть временной сдвиг не 24 часа а на ~12, тогда нужно будет посмотреть утром ещё раз

**Comment by brandonzorn** [comment]
Если я у себя запускаю проект то предыдущий день выбрать нельзя

На сайте datanar.ru
![изображение](https://github.com/Gray-Advantage/Datanar-Django/assets/68778953/c57fd868-8dd6-40ca-9b02-67f12fdbf3b5)

Localhost
![изображение](https://github.com/Gray-Advantage/Datanar-Django/assets/68778953/d5ce930b-0a00-4eae-a73d-36a725893528)

**Comment by Gray-Advantage** [comment]
Ахах, а теперь нельзя, я пока не понимаю как так происходит)

**Comment by Gray-Advantage** [comment]
Так, я сейчас на сервере добавил логирование того места, которое мне кажется является проблемным, нужно ещё раз дождаться когда идёт расхождения серверного времени от пользовательского (и пользователь может указать дату в прошлое) и посмотреть как сервер считает время у себя и у пользователя в этот момент

**Comment by Gray-Advantage** [comment]
Так, теперь эти фокусы должны прекратится (я надеюсь)
