### ISSUE TITLE
Добавить описание проекта

### ISSUE THREAD

**Issue by brandonzorn** [Gray-Advantage/Datanar-Django#30]
![изображение](https://github.com/Gray-Advantage/Datanar-Django/assets/68778953/ab9a2de0-d127-4a4a-8d3f-1260b4916586)

# Добавить описание и темы

## topics: 

url-shortener
shorten-urls
web-application
django
python
django-rest-framework

**Comment by Gray-Advantage** [comment]
Думаю, этого будет достаточно
