### ISSUE TITLE
Блокировка адресов

### ISSUE THREAD

**Issue by brandonzorn** [Gray-Advantage/Datanar-Django#48]
Блокировка адресов не работает если в адрес добавить www
Например https://www.clck.ru/
![изображение](https://github.com/user-attachments/assets/402b745c-909a-4575-8b3f-195de53c4d44)
![изображение](https://github.com/user-attachments/assets/9352605a-a128-4dc7-acb5-2d5b4db09365)

**Comment by Gray-Advantage** [comment]
Просто регулярки на сайте в панели управления это не учитывали. Исправлено
